In [1]:
import numpy as np
import torch
import sys

In [2]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

In [3]:
set_seed(42)

arr = np.random.randint(0, 5, size = 6)
print(arr)

[3 4 2 4 4 1]


In [4]:
x = torch.tensor(arr)

In [5]:
print(x)

tensor([3, 4, 2, 4, 4, 1])


In [6]:
x = x.to(torch.int64)

# for checking
print(x.dtype)

torch.int64


In [7]:
x = x.view(3, 2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [8]:
right = x[:, 1]
print(right)

tensor([4, 4, 1])


In [9]:
squared = x**2
print(squared)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [10]:
set_seed(42)
y = torch.randint(0,5, (2, 3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [11]:
prod = torch.matmul(x,y)
print(prod)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
