## LABORATORY TASK 5

**Name:** Chris Jallaine Mugot <br>
**Section:** DS4A <br>
**Date:** September 3, 2025

---

**1. Perform Standard Imports**

In [1]:
import numpy as np
import torch
import sys

**2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.**

In [45]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.**

In [46]:
set_seed(42)

arr = np.random.randint(0, 5, size = 6)
print(arr)

[3 4 2 4 4 1]


**4. Create a tensor "x" from the array above**

In [47]:
x = torch.tensor(arr)

In [48]:
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


**5. Change the dtype of x from int32 to int64**

In [49]:
x = x.to(torch.int64)

# for checking
print(x.dtype)

torch.int64


**6. Reshape x into a 3x2 tensor. <br>
(There are several ways to do this.)**

In [50]:
x = x.view(3, 2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

**7. Return the right-hand column of tensor x**

In [51]:
right = x[:, 1]
print(right)

tensor([4, 4, 1])


**8. Without changing x, return a tensor of square values of x. <br>**
*There are several ways to do this.*

In [52]:
squared = x**2
print(squared)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


**9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x** <br>
*Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.* <br>

Think about what shape it should have to permit matrix multiplication.

In [53]:
set_seed(42)
y = torch.randint(0,5, (2, 3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


**Explanation:**

This is in explanation for why the y tensor is in 2X3 dimension instead of the same 3X2 used in our X. Our x that was previously reshaped as a 3X2 dimension tensor should be multiplied with our y now. The thing is when we are multiplying a matrix to another matrix, we need to do the dot product of rows and columns, that means that a 3X2 tensor should be multiplied to a 2X3 tensor, to work out the answer for the 1st row and 1st column multiplication. 

**10. Find the matrix product of x and y.**

In [54]:
prod = torch.matmul(x,y)
print(prod)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


---